### ISSUE TITLE
$word instead of $prev?

### ISSUE THREAD

**Issue by luklapp** [aheissenberger/php-sentimentanalyser#1]
Hey! Thanks for sharing php-sentimentanalyser, I really like it! But there might be an issue in src/Sentiment.php, line 72:

`$score = ( preg_match($this->negate, $word) ? -$this->dict[$word] : $this->dict[$word] );`

I think this should be:

`$score = ( preg_match($this->negate, $prev) ? -$this->dict[$word] : $this->dict[$word] );`
(`$prev` instead of `$word`)

**Comment by aheissenberger** [comment]
Thank you - got fixed in the last release
